-------------------------------------------------------------------------------
Test set: com.soecode.lyf.dao.AppointmentDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.876 s <<< FAILURE! - in com.soecode.lyf.dao.AppointmentDaoTest
testInsertAppointment(com.soecode.lyf.dao.AppointmentDaoTest)  Time elapsed: 1.113 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testInsertAppointment(AppointmentDaoTest.java:16)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testInsertAppointment(AppointmentDaoTest.java:16)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testInsertAppointment(AppointmentDaoTest.java:16)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testInsertAppointment(AppointmentDaoTest.java:16)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.soecode.lyf.dao.AppointmentDaoTest.testInsertAppointment(AppointmentDaoTest.java:16)

testQueryByKeyWithBook(com.soecode.lyf.dao.AppointmentDaoTest)  Time elapsed: 0.976 s  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: 
nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [E:\Github Repos\springMVCDemo\target\classes\mapper\AppointmentDao.xml]
### The error may involve com.soecode.lyf.dao.AppointmentDao.queryByKeyWithBook
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testQueryByKeyWithBook(AppointmentDaoTest.java:24)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 

### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
### The error may exist in file [E:\Github Repos\springMVCDemo\target\classes\mapper\AppointmentDao.xml]
### The error may involve com.soecode.lyf.dao.AppointmentDao.queryByKeyWithBook
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testQueryByKeyWithBook(AppointmentDaoTest.java:24)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testQueryByKeyWithBook(AppointmentDaoTest.java:24)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.soecode.lyf.dao.AppointmentDaoTest.testQueryByKeyWithBook(AppointmentDaoTest.java:24)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.soecode.lyf.dao.AppointmentDaoTest.testQueryByKeyWithBook(AppointmentDaoTest.java:24)

